name: Deploy to patreon server
on:
  push:
    branches:
    - main
jobs:
  upload_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: LFTP deploy action
      uses: xarses/lftp-upload-action@v0.2.0
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        ssl_verify_cert: no
        protocol: sftp
        local_path: minecraft/config/betterquesting/
        remote_path: custom-minecraft/config/betterquesting/
        mirror_args: --no-perms

