name: Deploy to patreon server
on:
  push:
    branches: [main]
jobs:
  upload_files:
    steps:
    - uses: actions/checkout@v2

    - name: LFTP deploy action
      uses: xarses/lftp-upload-action@v0.0.1
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local_path: minecraft/config/betterquesting/
        remote_path: custom-minecraft/config/betterquesting/

